### ISSUE TITLE
Update for pytorch 1.3.1

### ISSUE THREAD

**Issue by jhmenke** [apozas/ebm-torch#3]
Hello,

i saw this awesome library and wanted to test the examples, but right now both seem to have issues.

The RBM example runs through but produces a completely black image as the output.
The DBN example stops at the fine-tuning stage

```Traceback (most recent call last):
  File ".../ebm-torch/dbn_example.py", line 84, in <module>
    batch_size=batch_size)
  File ".../ebm-torch/ebm/models.py", line 310, in finetune
    v_sample = self.sampler.get_v_sample(wakepos_samples[-2],
AttributeError: 'PersistentContrastiveDivergence' object has no attribute 'get_v_sample'
```

I hope this would be relatively easy to fix?

**Comment by jhmenke** [comment]
Regarding the second issue, i added this in samples.py under Sampler:

```    
def get_v_sample(self, v0, weights, vbias, hbias):
        return self.get_negative_sample(v0, weights, vbias, hbias)
```

It _seems_ to work.

However, it also produces a completely black image.

**Comment by jhmenke** [comment]
The floats have to be multiplied by 255 for anything to become visible.
